version: '3'
services:
  postgres:
    image: postgres:16-alpine
    ports:
      - 5432:5432
    volumes:
      - ./postgres-data:/var/lib/postgresql/data
    environment:
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_DB=chat

  redis:
    image: redis
    ports:
      - 6379:6379
    restart: always
    volumes:
      - ./redis-data:/data