# Generated by Django 5.0.6 on 2024-05-26 02:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0002_messages_created_at'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Messages',
        ),
    ]
